<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-options.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'allow_change_usernames' => 'Viestej‰ l‰hett‰neill‰ k‰ytt‰jill‰ oikeus vaihtaa tunnustaan:',
		'allow_close_questions' => 'Kysymysten sulkeminen k‰sin sallittua:',
		'allow_login_email_only' => 'Kirjautuminen vain s‰hkˆpostiosoitteella (ei k‰ytt‰j‰tunnuksella):', 
		'allow_multi_answers' => 'Useampi vastaus yhdelt‰ k‰ytt‰j‰lt‰:',
		'allow_no_category' => 'Kysymyksell‰ ei tarvitse olla kategoriaa',
		'allow_no_sub_category' => 'Kysymyksell‰ voi olla kategoria, mutta ei alikategoriaa',
		'allow_private_messages' => 'Salli yksityisviestien l‰hett‰minen k‰ytt‰jien kesken:',
		'allow_self_answer' => 'K‰ytt‰j‰t voivat vastata omiin kysymyksiins‰:',
		'allow_view_q_bots' => 'Hakukoneet n‰kev‰t kysymyssivut',
		'avatar_allow_gravatar' => 'Salli ^1Gravatar^2-kuvat:',
		'avatar_allow_upload' => 'K‰ytt‰j‰t voivat ladata oman profiilikuvan:',
		'avatar_default_show' => 'Oletusprofiilikuva:',
		'avatar_profile_size' => 'Profiilikuvan koko profiilisivulla:',
		'avatar_q_list_size' => 'Profiilikuvan koko kysymyslistoissa:',
		'avatar_q_page_a_size' => 'Profiilikuvan koko vastauksissa:',
		'avatar_q_page_c_size' => 'Profiilikuvan koko kommenteissa:',
		'avatar_q_page_q_size' => 'Profiilikuvan koko kysymyksiss‰:',
		'avatar_store_size' => 'Profiilikuvan maksimitallennuskoko:',
		'avatar_users_size' => 'Profiilikuvan koko parhaiden k‰ytt‰jien sivulla:',
		'block_bad_words' => 'Sensuroidut sanat - erota v‰lilyˆnnill‰ tai pilkulla:',
		'block_ips_write' => 'Torjutut IP-osoitteet - erota v‰lilyˆnnill‰ tai pilkulla:',
		'captcha_module' => 'K‰yt‰ captcha-moduulia:',
		'captcha_on_anon_post' => 'K‰yt‰ captchaa anonyymeiss‰ viesteiss‰:',
		'captcha_on_feedback' => 'K‰yt‰ captchaa palautesivulla:',
		'captcha_on_register' => 'K‰yt‰ captchaa k‰ytt‰jien rekisterˆinniss‰:',
		'captcha_on_reset_password' => 'K‰yt‰ captchaa salasanana nollaussivulla:',
		'captcha_on_unconfirmed' => 'K‰yt‰ captchaa, jos s‰hkˆpostia ei ole vahvistettu:',
		'columns_tags' => 'Sarakkeet Tagit-sivulla:',
		'columns_users' => 'Sarakkeet K‰ytt‰j‰t-sivulla:',
		'comment_on_as' => 'Vastausten kommentointi:',
		'comment_on_qs' => 'Kysymysten kommentointi:',
		'confirm_user_emails' => 'Pyyd‰ vahvistus k‰ytt‰jien s‰hkˆposteille:',
		'confirm_user_required' => 'Uusien k‰ytt‰jien pit‰‰ suorittaa vahvistus:',
		'custom_home_content' => 'Kotisivun sis‰ltˆ - HTML sallittua:',
		'custom_home_heading' => 'Kotisivun otsikko:',
		'default_privacy' => 'Yksityisyyssuoja: S‰hkˆpostiosoitettasi ei v‰litet‰ tai myyd‰ kenellek‰‰n.',
		'default_sidebar' => "Welcome to ^, where you can ask questions and receive answers from other members of the community.",
		'default_subject' => 'Viesti k‰ytt‰j‰lt‰ ^',
		'default_suffix' => 'K&V',
		'do_ask_check_qs' => 'Tarkista samankaltaiset kysymykset kysytt‰ess‰:',
		'do_close_on_select' => 'Sulje kysymykset, joilla hyv‰ksytty vastaus:',
		'do_complete_tags' => 'N‰yt‰ sopivat tagit kirjoittamisen aikana:',
		'do_count_q_views' => 'Laske, montako kertaa kysymys on n‰hty:',
		'do_example_tags' => 'N‰yt‰ kysymykseen sopivat esimerkkitagit:',
		'editor_for_as' => 'Vastausten oletuseditori:',
		'editor_for_cs' => 'Kommenttien oletuseditori:',
		'editor_for_qs' => 'Kysymysten oletuseditori:',
		'email_privacy' => 'Yksityisyysviesti s‰hkˆpostiosoitteille - HTML sallittu:',
		'extra_field_active' => 'Yksilˆllinen kentt‰ kysymyslomakkeen lis‰tiedoille:',
		'extra_field_display_label' => 'Show the extra information on question pages with label:',
		'extra_field_display' => 'Show the extra information on question pages',
		'feed_for_activity' => 'Tuoreimpien tapahtumien syˆte:',
		'feed_for_hot' => 'Kuumimpien kysymysten syˆte:',
		'feed_for_qa' => 'Tuoreiden kysymysten ja vastausten syˆte:',
		'feed_for_questions' => 'Tuoreiden kysymysten syˆte:',
		'feed_for_search' => 'Hakutulosten syˆte:',
		'feed_for_tag_qs' => 'Jokaisella tagilla oma syˆte:',
		'feed_for_unanswered' => 'Vastaamattomien kysymysten syˆte:',
		'feed_full_text' => 'Sis‰llyt‰ koko teksti syˆtteiss‰:',
		'feed_number_items' => 'Syˆtteiden maksimipituus:',
		'feed_per_category' => 'Jokaisella kategorialla oma syˆte:',
		'feedback_email' => 'Yll‰pidon s‰hkˆpostiosoite - ei n‰ytet‰ k‰ytt‰jille:',
		'feedback_enabled' => 'Salli k‰ytt‰jien palautteet',
		'flagging_hide_after' => 'Automatically hide posts which reach:',
		'flagging_notify_every' => 'Email me again after every additional:',
		'flagging_notify_first' => 'Email me if a post receives:',
		'flagging_of_posts' => 'Allow posts to be flagged:',
		'follow_on_as' => 'Allow questions to be related to answers:',
		'from_email' => 'Sender address for messages from site:',
		'hot_weight_a_age' => 'Kysymyksell‰ on uusi vastaus:',
		'hot_weight_answers' => 'Kysymyksell‰ on monta vastausta:',
		'hot_weight_q_age' => 'Kysymys on uusi:',
		'hot_weight_views' => 'Kysymyst‰ on katsottu usein:',
		'hot_weight_votes' => 'Kysymyksell‰ on monta ‰‰nt‰:',
		'links_in_new_window' => 'Open linked URLs in a new window:',
		'logo_height' => 'Logon korkeus:',
		'logo_show' => 'N‰yt‰ logo sivun otsiko-osassa',
		'logo_url' => 'Logon URL - absoluuttinen tai suhteessa Q2A:n juureen:',
		'logo_width' => 'Logon leveys:',
		'mailing_body' => 'Leip‰teksti:',
		'mailing_enabled' => 'Salli massapostitukset kaikille k‰ytt‰jille',
		'mailing_from_email' => 'S‰hkˆpostiosoitteesta:',
		'mailing_from_name' => 'Nimi:',
		'mailing_per_minute' => 'Suurin sallittu postitusnopeus:',
		'mailing_subject' => 'Otsikko:',
		'match_1' => 'Kapein',
		'match_2' => 'Kapeampi',
		'match_3' => 'Oletus',
		'match_4' => 'Leve‰mpi',
		'match_5' => 'Levein',
		'match_ask_check_qs' => 'Similar questions matching:',
		'match_example_tags' => 'Example tags matching:',
		'match_related_qs' => 'Related questions matching:',
		'max_len_q_title' => 'Kysymyksen otsikon suurin sallittu pituus:',
		'max_num_q_tags' => 'Suurin sallittu m‰‰r‰ tageja:',
		'max_rate_ip_as' => 'Rate limit for adding answers:',
		'max_rate_ip_cs' => 'Rate limit for posting comments:',
		'max_rate_ip_flags' => 'Rate limit for flagging posts:',
		'max_rate_ip_logins' => 'Rate limit for logging in:',
		'max_rate_ip_messages' => 'Rate limit for sending private messages:',
		'max_rate_ip_qs' => 'Rate limit for asking questions:',
		'max_rate_ip_registers' => 'Rate limit for user registrations:',
		'max_rate_ip_uploads' => 'Rate limit for uploading files:',
		'max_rate_ip_votes' => 'Rate limit for voting:',
		'max_rate_user_as' => 'Enimm‰ism‰‰r‰ vastauksia per k‰ytt‰j‰ per tunti:',
		'max_rate_user_cs' => 'Enimm‰ism‰‰r‰ kommentteja per k‰ytt‰j‰ per tunti:',
		'max_rate_user_flags' => 'Maximum flags per user per hour:',
		'max_rate_user_messages' => 'Enimm‰ism‰‰r‰ yksityisviestej‰ per k‰ytt‰j‰ per tunti:',
		'max_rate_user_qs' => 'Enimm‰ism‰‰r‰ kysymyksi‰ per k‰ytt‰j‰ per tunti:',
		'max_rate_user_uploads' => 'Enimm‰ism‰‰r‰ tiedostonl‰hetyksi‰ per k‰ytt‰j‰ per tunti:',
		'max_rate_user_votes' => 'Enimm‰ism‰‰r‰ ‰‰ni‰ per k‰ytt‰j‰ per tunti:',
		'min_len_a_content' => 'Vastauksen v‰himm‰ispituus:',
		'min_len_c_content' => 'Kommentin v‰himm‰ispituus:',
		'min_len_q_content' => 'Kysymyksen leip‰tekstin minimipituus:',
		'min_len_q_title' => 'Kysymysotsikon v‰himm‰ispituus:',
		'min_num_q_tags' => 'V‰himm‰ism‰‰r‰ tageja:',
		'moderate_anon_post' => 'Moderoi anonyymeja viestej‰:',
		'moderate_by_points' => 'Moderoi k‰ytt‰ji‰, joilla v‰h‰n pisteit‰:',
		'moderate_notify_admin' => 'L‰het‰ minulle s‰hkˆpostia, kun viesti vaatii moderointia:',
		'moderate_points_limit' => 'Use moderation for users with less than:',
		'moderate_unconfirmed' => 'Moderoi, jos s‰hkˆpostia ei ole varmistettu:',
		'neat_urls' => 'URL-rakenne:',
		'notify_admin_q_post' => 'Email this address when a question is posted',
		'notify_users_default' => 'Check email notification box by default:',
		'option_default' => 'Oletus',
		'page_size_activity' => 'Length of All Activity page:',
		'page_size_ask_check_qs' => 'Maximum similar questions to show:',
		'page_size_ask_tags' => 'Maximum tag hints to show:',
		'page_size_home' => 'K&V-sivun pituus:',
		'page_size_hot_qs' => 'Kuumaa!-sivun pituus:',
		'page_size_q_as' => 'Enimm‰ism‰‰r‰ vastauksia per sivu:',
		'page_size_qs' => 'Kysymyssivun pituus:',
		'page_size_related_qs' => 'Maximum related questions:',
		'page_size_search' => 'Hakutuloksia per sivu:',
		'page_size_tag_qs' => 'Kysymysten m‰‰r‰ tagisivuilla:',
		'page_size_tags' => 'Tagisivun pituus:',
		'page_size_una_qs' => 'Vastaamattomien kysymysten sivun pituus:',
		'page_size_user_posts' => 'Viestin m‰‰r‰ k‰ytt‰jien sivulla:',
		'page_size_users' => 'K‰ytt‰j‰t-sivun pituus:',
		'pages_prev_next' => 'Linkki edelliselle/seuraavalle sivulle:',
		'permit_admins' => 'Yll‰pit‰j‰t',
		'permit_all' => 'Kuka tahansa',
		'permit_block' => 'Blocking or unblocking user or IPs:',
		'permit_confirmed' => 'Registered users with email confirmed',
		'permit_create_admins' => 'Creating administrators:',
		'permit_create_eds_mods' => 'Creating editors and moderators:',
		'permit_create_experts' => 'Creating experts:',
		'permit_delete_users' => 'Deleting users:',
		'permit_editors' => 'Editors, Moderators, Admins',
		'permit_experts' => 'Experts, Editors, Moderators, Admins',
		'permit_moderators' => 'Moderators and Admins',
		'permit_points_confirmed' => 'Registered & email confirmed & enough points',
		'permit_points' => 'Registered users with enough points',
		'permit_see_emails' => 'Viewing user email addresses:',
		'permit_supers' => 'P‰‰yll‰pit‰j‰',
		'permit_users' => 'Rekisterˆidyt k‰ytt‰j‰t',
		'place_full_below_content' => 'Full width - Below content',
		'place_full_below_footer' => 'Full width - Below footer',
		'place_full_below_nav' => 'Full width - Below navigation',
		'place_full_top' => 'Full width - Top of page',
		'place_main_below_lists' => 'Main area - Below lists',
		'place_main_below_title' => 'Main area - Below title',
		'place_main_bottom' => 'Main area - Bottom',
		'place_main_top' => 'Main area - Top',
		'place_side_below_categories' => 'Side panel - Below categories',
		'place_side_below_sidebar' => 'Side panel - Below sidebar box',
		'place_side_last' => 'Side panel - Last',
		'place_side_top' => 'Side panel - Top',
		'points_a_selected' => 'Having your answer selected as the best:',
		'points_a_voted_max_gain' => 'Limit from up votes on each answer:',
		'points_a_voted_max_loss' => 'Limit from down votes on each answer:',
		'points_base' => 'Lis‰‰ kaikille k‰ytt‰jille:',
		'points_multiple' => 'Kerro kaikki pisteet:',
		'points_per_a_voted_down' => 'Per down vote on your answer:',
		'points_per_a_voted_up' => 'Per up vote on your answer:',
		'points_per_q_voted_down' => 'Per down vote on your question:',
		'points_per_q_voted_up' => 'Per up vote on your question:',
		'points_post_a' => 'Posting an answer:',
		'points_post_q' => 'Posting a question:',
		'points_q_voted_max_gain' => 'Limit from up votes on each question:',
		'points_q_voted_max_loss' => 'Limit from down votes on each question:',
		'points_select_a' => 'Selecting an answer for your question:',
		'points_vote_down_a' => 'Voting down an answer:',
		'points_vote_down_q' => 'Voting down a question:',
		'points_vote_up_a' => 'Voting up an answer:',
		'points_vote_up_q' => 'Voting up a question:',
		'q_urls_remove_accents' => 'Remove accents from question URLs:',
		'q_urls_title_length' => 'Question title length in URLs:',
		'search_module' => 'Use search module:',
		'show_a_form_immediate' => 'Show answer form immediately:',
		'show_always' => 'Always',
		'show_c_reply_buttons' => 'Show reply button on comments:',
		'show_custom_answer' => 'Custom message on answer form - HTML allowed:',
		'show_custom_ask' => 'Custom message on ask form - HTML allowed:',
		'show_custom_comment' => 'Custom message on comment form - HTML allowed:',
		'show_custom_footer' => 'Custom HTML at bottom of every page:',
		'show_custom_header' => 'Custom HTML at top of every page:',
		'show_custom_home' => 'Custom content in home page instead of Q&A',
		'show_custom_in_head' => 'Custom HTML in <HEAD> section of every page:',
		'show_custom_register' => 'Custom message on register form - HTML allowed:',
		'show_custom_sidebar' => 'Custom HTML in sidebar box on every page:',
		'show_custom_sidepanel' => 'Custom HTML in side panel on every page:',
		'show_custom_welcome' => 'Custom message in email sent to new registered users:',
		'show_fewer_cs_count' => 'If partially hidden, show most recent:',
		'show_fewer_cs_from' => 'Partially hide comments if more than:',
		'show_full_date_days' => 'Show full date after:',
		'show_home_description' => 'Include <META> description for home page:',
		'show_if_no_as' => 'If no answers',
		'show_message_history' => 'Store and display private message history:',
		'show_never' => 'Never',
		'show_notice_visitor' => 'Notice at top for first time visitors - HTML allowed:',
		'show_notice_welcome' => 'Notice at top for new registered users - HTML allowed:',
		'show_selected_first' => 'Move selected answer to the top:',
		'show_url_links' => 'Detect and link URLs in posts:',
		'show_user_points' => 'Show points next to usernames:',
		'show_user_titles' => 'Show titles next to usernames:',
		'show_view_counts' => 'Show view count in question lists:',
		'show_when_created' => 'Show age of user posts:',
		'site_language' => 'Sivuston kieli:',
		'site_maintenance' => 'Take site down for temporary maintenance',
		'site_theme_mobile' => 'Theme for mobiles:',
		'site_theme' => 'Sivuston teema:',
		'site_title' => 'K&V-sivun otsikko',
		'site_url' => 'Preferred site URL:',
		'smtp_active' => 'L‰het‰ s‰hkˆpostit SMTP:n kautta paikallisen palvelimen sijaan',
		'smtp_address' => 'SMTP-palvelimen osoite:',
		'smtp_authenticate' => 'L‰het‰ SMTP-tunnus ja -salasana',
		'smtp_password' => 'SMTP-salasana:',
		'smtp_port' => 'SMTP-palvelimen portti:',
		'smtp_secure_none' => 'Ei mit‰‰n',
		'smtp_secure' => 'SMTP suojattu yhteys:',
		'smtp_username' => 'SMTP-tunnus:',
		'sort_answers_by' => 'Lajittele vastaukset:',
		'sort_time' => 'Aika',
		'sort_votes' => 'ƒ‰net',
		'suspend_register_users' => 'Keskeyt‰ v‰liaikaisesti uusien k‰ytt‰jien rekisterˆityminen:',
		'tag_separator_comma' => 'Salli vain pilkku tagierottimena:',
		'tags_or_categories' => 'Kysymysten luokittelu:',
		'votes_separated' => 'N‰yt‰ erikseen plus- ja miinus‰‰net:',
		'voting_on_as' => 'Salli vastausten ‰‰nest‰minen:',
		'voting_on_q_page_only' => 'Salli ‰‰nest‰minen vain kysymyssivulla:',
		'voting_on_qs' => 'Salli kysymysten ‰‰nest‰minen:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/