<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-admin.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'active_widgets_explanation' => 'Aktiiviset widgetit:',
		'add_category_button' => 'Lisää kategoria',
		'add_field_button' => 'Lisää kenttä',
		'add_link_button' => 'Lisää linkki',
		'add_link_link' => ' - ^1lisää linkki^2',
		'add_new_field' => 'Lisää uusi kenttä',
		'add_new_title' => 'Lisää uusi otsikko',
		'add_page_button' => 'Lisää sivu',
		'add_title_button' => 'Lisää otsikko',
		'add_widget_button' => 'Lisää widgetti',
		'add_widget_link' => ' - ^1lisää widgetti^2',
		'admin_title' => 'Ylläpitokeskus',
		'after_footer' => 'Linkit alaviitteen jälkeen',
		'after_main_menu' => 'Yläosan välilehtien jälkeen',
		'after_x_tab' => ' Välilehden "^" jälkeen',
		'after_x' => 'After "^"',
		'moderate_title' => 'Moderointi',
		'basic_editor' => 'Peruseditori',
		'before_main_menu' => 'Ennen yläosan välilehtiä',
		'block_ips_note' => 'Use a hyphen for ranges or * to match any number. Examples: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_words_note' => 'Use a * to match any letters. Examples: doh (will only match exact word doh) , doh* (will match doh or dohno) , do*h (will match doh, dooh, dough).',
		'cancel_mailing_button' => 'Peruuta postitus',
		'categories_introduction' => 'Klikkaa \'Lisää kategoria\'-nappia alkuun pääsemiseksi.',
		'categories_not_shown' => 'Joillakin kysymyksillä on kategorioita, joita ei tulla näyttämään..',
		'categories_title' => 'Kategoriat',
		'categories' => 'Kategoriat',
		'category_add_sub' => 'lisää alikategoria',
		'category_added' => 'Kategoria lisätty',
		'category_already_used' => 'Tämä on jo käytössä jossain kategoriassa',
		'category_default_slug' => 'kategoria-^',
		'category_description' => 'Vapaavalintainen kuvaus kategorialle:',
		'category_max_depth_x' => 'Jotkut asetukset saattavat olla piilotettuna, jotta kategoriat eivät yllä syvemmällä kuin tasolle ^.',
		'category_move_parent' => 'move to different parent',
		'category_name_first' => 'Ensimmäisen kategorian nimi:',
		'category_name' => 'Kategorian nimi:',
		'category_no_add_subs_x' => 'This category cannot have sub-categories because it is already ^ levels down.',
		'category_no_delete_subs' => 'Tätä kategoriaa ei voi poistaa, koska sillä on alikategorioita.',
		'category_no_sub_error' => '^q question/s in this category have no sub-category - ^1set sub-category^2',
		'category_no_sub_to' => 'Move questions in ^ with no sub-category to:',
		'category_no_subs' => 'Ei mitään',
		'category_none_error' => '^q question/s currently have no category - ^1set category^2',
		'category_none_to' => 'Siirrä kysymykset, joilla ei ole kategoriaa, kategoriaan:',
		'category_parent' => 'Parent category:',
		'category_saved' => 'Kategoria on tallennettu',
		'category_slug' => 'Category slug - URL fragment:',
		'category_subs' => 'Alikategoriat:',
		'category_top_level' => 'No parent (top level)',
		'characters' => 'merkkiä',
		'check_language_suffix' => ' - ^1tarkista kielitiedostot^2',
		'click_name_edit' => 'Yksilöidyt sivut tai linkit:',
		'database_cleanup' => 'Tietokannan puhdistusoperaatiot',
		'delete_category_reassign' => 'Poista tämä kategoria ja siirrä kysymykset kategoriaan:',
		'delete_category' => 'Poista tämä kategoria',
		'delete_field' => 'Poista tämä kenttä',
		'delete_hidden_complete' => 'Kaikki piilotetut viestit, joilla ei ollut riippuvuuksia, on poistettu',
		'delete_hidden_note' => ' - kaikki piilotetut kysymykset, vastaukset ja kommentit, joilla ei ole riippuvuuksia',
		'delete_hidden' => 'Poista piilotetut viestit',
		'delete_link' => 'Poista tämä linkki',
		'delete_page' => 'Poista tämä sivu',
		'delete_stop' => 'Lopeta poistaminen',
		'delete_title' => 'Poista tämä otsikko',
		'delete_widget_position' => 'Poista widgetti tästä paikasta',
		'edit_custom_page' => 'Muokkaa yksilöityä sivua',
		'edit_field' => ' - ^1muokkaa kenttää^2',
		'edit_link' => ' - ^1muokkaa linkkiä^2',
		'edit_page' => ' - ^1muokkaa sivua^2',
		'edit_title' => ' - ^1muokkaa otsikkoa^2',
		'emails_per_minute' => 'sähköpostia minuutissa',
		'emails_title' => 'Sähköpostit',
		'feed_link_example' => 'Esimerkkisyöte',
		'feed_link' => 'Syöte',
		'feeds_title' => 'RSS-syötteet',
		'field_link_url' => 'Linkattu URL',
		'field_multi_line' => 'Useita rivejä tekstiä',
		'field_name' => 'Kentän nimi:',
		'field_single_line' => 'Yksi rivi tekstiä',
		'field_type' => 'Sisällön tyyppi:',
		'first' => 'Ensimmäinen',
		'flagged_title' => 'Liputukset',
		'from_anon' => 'Anonyymiltä:',
		'from_users' => 'Käyttäjiltä:',
		'general_title' => 'Yleiset',
		'hidden_answers_deleted' => 'Deleted ^1 of ^2 hidden answers without dependents...',
		'hidden_comments_deleted' => 'Deleted ^1 of ^2 hidden comments...',
		'hidden_questions_deleted' => 'Deleted ^1 of ^2 hidden questions without dependents...',
		'hotness_factors' => 'Suhteellinen tärkeys kysymyksen kuumuudelle:',
		'hidden_title' => 'Piilotetut',
		'installed_plugins' => 'Asennetut lisäosat:',
		'ip_address_pages' => 'IP address pages',
		'layout_title' => 'Asemointi',
		'link_name' => 'Linkin teksti:',
		'link_new_window' => 'Avaa linkki uuteen ikkunaan',
		'link_url' => 'Linkin URL - absoluuttinen tai suhteellinen sivuston juureen nähden:',
		'lists_title' => 'Listat',
		'mailing_complete' => 'Postitus on suoritettu',
		'mailing_explanation' => 'Käyttäjät voivat lopettaa tilauksen tilisivultaan.',
		'mailing_progress' => 'Mailing completed for ^1 of ^2 users...',
		'mailing_title' => 'Postitus',
		'mailing_unsubscribe' => 'Tilauksen peruuttamislinkki lisätään jokaisen viestin alaosaan.',
		'maintenance_admin_only' => 'Sivustosi on ^1ylläpitotilassa^2 eikä ole tavallisten käyttäjien käytettävissä tällä hetkellä.',
		'maximum_x' => ' (maks. ^)',
		'module_x_database_init' => 'The ^1 ^2 module requires some ^3database initialization^4.',
		'most_flagged_title' => 'Flagged content',
		'mysql_version' => 'MySQL-versio:',
		'nav_links_explanation' => 'Show navigation links:',
		'nav_qa_is_home' => 'Q&A (links to home page)',
		'neat_urls_note' => ' (vaatii ^1htaccess^2-tiedoston)',
		'no_approve_found' => 'No content is waiting for approval',
		'no_classification' => 'Ei mitään',
		'no_flagged_found' => 'No flagged content found',
		'no_hidden_found' => 'Piilotettua sisältöä ei löytynyt',
		'no_image_gd' => 'The installed version of PHP was compiled without GD image support, so users cannot upload their avatars directly.',
		'no_link' => 'Ei linkkiä',
		'no_multibyte' => 'The installed version of PHP was compiled without multibyte string support. Searching will be less effective for non-Roman characters.',
		'no_plugin_options' => 'Yhdelläkään asentamallasi lisäosalla ei ole lisäasetuksia.',
		'no_privileges' => 'Vain ylläpitäjillä on pääsy tälle sivulle.',
		'not_logged_in' => 'Ole hyvä ja ^1kirjaudu sisään^2 ylläpitäjänä nähdäksesi tämän sivun.',
		'opposite_main_menu' => 'Far end of tabs at top',
		'options_reset' => 'Asetukset palautettu',
		'options_saved' => 'Asetukset talletettu',
		'options' => 'asetukset',
		'page_already_used' => 'Joku sivu käyttää jo tätä',
		'page_content_html' => 'Sivulla näytettävä sisältä - HTML sallittua:',
		'page_default_slug' => 'sivu-^',
		'page_heading' => 'Heading to display at top of page:',
		'page_name' => 'Sivun nimi (käytetään myös välilehden ja linkin nimenä):',
		'page_slug' => 'Page slug (URL fragment):',
		'pages_explanation' => 'Click the \'Add Page\' button to add custom content to your Q2A site, or \'Add Link\' to link to any other web page.',
		'pages_title' => 'Sivut',
		'pause_mailing_button' => 'Keskeytä lähetys',
		'per_ip_hour' => 'per IP/hour',
		'per_user_hour' => 'per user/hour',
		'permissions_title' => 'Oikeudet',
		'permit_to_view' => 'Nähtävissä:',
		'php_version' => 'PHP-versio:',
		'pixels' => 'pikseliä',
		'plugin_module' => ' (lisäosamoduli: ^)',
		'plugin_pages_explanation' => 'Lisäosien kautta saatavilla olevat sivut:',
		'plugins_title' => 'Lisäosat',
		'points_defaults_shown' => 'Oletusasetukset nähtävillä alla, MUTTA NIITÄ EI OLE VIELÄ ASETETTU:',
		'points_required' => 'Arvonimen saamiseen vaadittavat pisteet:',
		'points_title' => 'Pisteet',
		'points' => 'pisteet',
		'position' => 'Sijainti:',
		'posting_title' => 'Lähettäminen',
		'profile_fields' => 'Lisäkentät käyttäjäprofiilissa:',
		'q2a_build_date' => 'Build date:',
		'q2a_db_size' => 'Tietokannan koko:',
		'q2a_db_version' => 'Q2A-tietokannan versio:',
		'q2a_latest_version' => 'Viimeisin versio:',
		'q2a_version' => 'Question2Answer-versio:',
		'question_lists' => 'Kysymyslistat',
		'question_pages' => 'Kysymyssivut',
		'recalc_categories_backpaths' => 'Recalculating URL paths for ^1 of ^2 categories...',
		'recalc_categories_complete' => 'Kaikki kategoriat laskettiin onnistuneesti uudelleen.',
		'recalc_categories_note' => ' - for post categories and category counts',
		'recalc_categories_recounting' => 'Recounting questions for ^1 of ^2 categories...',
		'recalc_categories_updated' => 'Recalculated for ^1 of ^2 posts...',
		'recalc_categories' => 'Laske kategoriat uudelleen',
		'recalc_points_complete' => 'Kaikki käyttäjien pisteet laskettiin onnistuneesti uudelleen.',
		'recalc_points_note' => ' - käyttäjärankingin ja pisteiden näyttämiseen',
		'recalc_points_recalced' => 'Recalculated for ^1 of ^2 users...',
		'recalc_points_usercount' => 'Arvioidaan käyttäjien kokonaismäärä...',
		'recalc_points' => 'Laske käyttäjien pisteet uudestaan',
		'recalc_posts_count' => 'Lasketaan kysymysten, vastausten ja kommenttien kokonaismäärä...',
		'recalc_stop' => 'Lopeta uudelleenlaskenta',
		'recent_approve_title' => 'Hyväksymistä odottava tuore sisältö',
		'recent_hidden_title' => 'Tuore, piilotettu sisältö',
		'recount_posts_as_recounted' => 'Recounted answers and hotness for ^1 of ^2 posts...',
		'recount_posts_complete' => 'Kaikki viestit laskettiin onnistuneesti uudelleen.',
		'recount_posts_note' => ' - the number of answers, votes, flags and hotness for each post',
		'recount_posts_stop' => 'Lopeta uudelleenlaskenta',
		'recount_posts_votes_recounted' => 'Recounted votes and flags for ^1 of ^2 posts...',
		'recount_posts' => 'Laske viestit uudelleen',
		'refill_events_complete' => 'All events streams were successfully refilled',
		'refill_events_note' => ' - for each user\'s list of updates',
		'refill_events_refilled' => 'Refilled for ^1 of ^2 questions...',
		'refill_events' => 'Refill event streams',
		'reindex_content' => 'Uudelleenindeksoi sisältö',
		'reindex_content_note' => ' - for searching and related question suggestions',
		'reindex_content_stop' => 'Lopeta uudelleenindeksointi',
		'reindex_pages_reindexed' => 'Reindexed ^1 of ^2 pages...',
		'reindex_posts_complete' => 'Kaikki viestit uudelleenindeksoitiin onnistuneesti.',
		'reindex_posts_reindexed' => 'Reindexed ^1 of ^2 posts...',
		'reindex_posts_wordcounted' => 'Recounted ^1 of ^2 words...',
		'requires_php_version' => 'Disabloitu - vaatii PHP-version ^ tai uudemman',
		'requires_q2a_version' => 'Disabloitu - vaatii Question2Answer-version ^ tai uudemman',
		'reset_options_button' => 'Palauta oletusasetukset',
		'resume_mailing_button' => 'Jatka lähettämistä',
		'save_options_button' => 'Tallenna asetukset',
		'save_recalc_button' => 'Tallenna ja laske uudestaan',
		'send_test_button' => 'Lähetä testi minulle',
		'show_defaults_button' => 'Näytä oletusarvot',
		'slug_bad_chars' => 'The slug may not contain these characters: ^',
		'slug_reserved' => 'This slug is reserved for use by another page',
		'spam_title' => 'Roskaposti',
		'start_mailing_button' => 'Aloita lähetys',
		'stats_title' => 'Tilastot',
		'stop_recalc_warning' => 'Tietokannan siivous on menossa. Jos suljet sivun, tämä operaatio keskeytetään.',
		'tag_pages' => 'Tagisivut',
		'tags_and_categories' => 'Tagit ja kategoriat',
		'tags_not_shown' => 'Joillakin kysymyksillä on tageja, joita ei tulla näyttämään näytetä.',
		'tags' => 'Tagit',
		'test_sent_to_x' => 'Testiviesti lähetettiin käyttäjälle ^',
		'title_already_used' => 'This value is already being used by another 	',
		'top_level_categories' => 'Ylimmän tason kategoriat:',
		'total_as' => 'Vastauksia yhteensä:',
		'total_cs' => 'Kommentteja yhteensä:',
		'total_qs' => 'Kysymyksiä yhteensä:',
		'unnamed_plugin' => 'Nimetön lisäosa',
		'upgrade_db' => 'Question2Answer-tietokantasi pitää ^1päivittää^2 tähän versioon.',
		'url_format_note' => 'Options with the ^ label are working for your site\'s configuration. For best search engine optimization (SEO), use the first ^ option available.',
		'user_pages' => 'Käyttäjäsivut',
		'user_title' => 'Käyttäjän otsikko - HTML sallittua:',
		'user_titles' => 'Pisteisiin perustuvat käyttäjien arvonimet:',
		'users_active' => 'Aktiiviset käyttäjät:',
		'users_must_have' => 'Käyttäjillä pitää olla',
		'users_posted' => 'Viestejä lähettäneet käyttäjät:',
		'users_registered' => 'Rekisteröityneet käyttäjät:',
		'users_title' => 'Käyttäjät',
		'users_voted' => 'Äänestäneet käyttäjät:',
		'version_get_x' => 'lataa ^',
		'version_requires_php' => '^1 vaatii PHP-versiota ^2', 
		'version_requires_q2a' => '^1 vaatii Q2A-versiota ^2', 
		'version_latest_unknown' => 'viimeisin tuntematon',
		'version_latest' => 'viimeisin',
		'viewing_title' => 'Katselu',
		'widget_all_pages' => 'Näytä widgetti tässä paikassa kaikilla käytössä olevilla sivuilla',
		'widget_global_options' => ' - ^1asetukset^2',
		'widget_name' => 'Widgetin nimi:',
		'widget_no_positions' => 'Tämä widgetti on jo lisätty jokaiseen mahdolliseen paikkaan.',
		'widget_not_available' => 'Tämä widgetti ei ole enää saatavilla. Tämä voi johtua siitä, että lisäosa, joka tarjoaa tämän widgetin ei ole enää asennettuna.',
		'widget_pages_explanation' => 'Näytä widgetti tässä paikassa seuraavilla sivuilla:',
		'widgets_explanation' => 'Tarjolla olevat widgetit:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/