<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-options.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'allow_change_usernames' => 'Viestejä lähettäneillä käyttäjillä oikeus vaihtaa tunnustaan:',
		'allow_close_questions' => 'Kysymysten sulkeminen käsin sallittua:',
		'allow_login_email_only' => 'Kirjautuminen vain sähköpostiosoitteella (ei käyttäjätunnuksella):', 
		'allow_multi_answers' => 'Useampi vastaus yhdeltä käyttäjältä:',
		'allow_no_category' => 'Kysymyksellä ei tarvitse olla kategoriaa',
		'allow_no_sub_category' => 'Kysymyksellä voi olla kategoria, mutta ei alikategoriaa',
		'allow_private_messages' => 'Salli yksityisviestien lähettäminen käyttäjien kesken:',
		'allow_self_answer' => 'Käyttäjät voivat vastata omiin kysymyksiinsä:',
		'allow_view_q_bots' => 'Hakukoneet näkevät kysymyssivut',
		'avatar_allow_gravatar' => 'Salli ^1Gravatar^2-kuvat:',
		'avatar_allow_upload' => 'Käyttäjät voivat ladata oman profiilikuvan:',
		'avatar_default_show' => 'Oletusprofiilikuva:',
		'avatar_profile_size' => 'Profiilikuvan koko profiilisivulla:',
		'avatar_q_list_size' => 'Profiilikuvan koko kysymyslistoissa:',
		'avatar_q_page_a_size' => 'Profiilikuvan koko vastauksissa:',
		'avatar_q_page_c_size' => 'Profiilikuvan koko kommenteissa:',
		'avatar_q_page_q_size' => 'Profiilikuvan koko kysymyksissä:',
		'avatar_store_size' => 'Profiilikuvan maksimitallennuskoko:',
		'avatar_users_size' => 'Profiilikuvan koko parhaiden käyttäjien sivulla:',
		'block_bad_words' => 'Sensuroidut sanat - erota välilyönnillä tai pilkulla:',
		'block_ips_write' => 'Torjutut IP-osoitteet - erota välilyönnillä tai pilkulla:',
		'captcha_module' => 'Käytä captcha-moduulia:',
		'captcha_on_anon_post' => 'Käytä captchaa anonyymeissä viesteissä:',
		'captcha_on_feedback' => 'Käytä captchaa palautesivulla:',
		'captcha_on_register' => 'Käytä captchaa käyttäjien rekisteröinnissä:',
		'captcha_on_reset_password' => 'Käytä captchaa salasanana nollaussivulla:',
		'captcha_on_unconfirmed' => 'Käytä captchaa, jos sähköpostia ei ole vahvistettu:',
		'columns_tags' => 'Sarakkeet Tagit-sivulla:',
		'columns_users' => 'Sarakkeet Käyttäjät-sivulla:',
		'comment_on_as' => 'Vastausten kommentointi:',
		'comment_on_qs' => 'Kysymysten kommentointi:',
		'confirm_user_emails' => 'Pyydä vahvistus käyttäjien sähköposteille:',
		'confirm_user_required' => 'Uusien käyttäjien pitää suorittaa vahvistus:',
		'custom_home_content' => 'Kotisivun sisältö - HTML sallittua:',
		'custom_home_heading' => 'Kotisivun otsikko:',
		'default_privacy' => 'Yksityisyyssuoja: Sähköpostiosoitettasi ei välitetä tai myydä kenellekään.',
		'default_sidebar' => "Welcome to ^, where you can ask questions and receive answers from other members of the community.",
		'default_subject' => 'Viesti käyttäjältä ^',
		'default_suffix' => 'K&V',
		'do_ask_check_qs' => 'Tarkista samankaltaiset kysymykset kysyttäessä:',
		'do_close_on_select' => 'Sulje kysymykset, joilla hyväksytty vastaus:',
		'do_complete_tags' => 'Näytä sopivat tagit kirjoittamisen aikana:',
		'do_count_q_views' => 'Laske, montako kertaa kysymys on nähty:',
		'do_example_tags' => 'Näytä kysymykseen sopivat esimerkkitagit:',
		'editor_for_as' => 'Vastausten oletuseditori:',
		'editor_for_cs' => 'Kommenttien oletuseditori:',
		'editor_for_qs' => 'Kysymysten oletuseditori:',
		'email_privacy' => 'Yksityisyysviesti sähköpostiosoitteille - HTML sallittu:',
		'extra_field_active' => 'Yksilöllinen kenttä kysymyslomakkeen lisätiedoille:',
		'extra_field_display_label' => 'Show the extra information on question pages with label:',
		'extra_field_display' => 'Show the extra information on question pages',
		'feed_for_activity' => 'Tuoreimpien tapahtumien syöte:',
		'feed_for_hot' => 'Kuumimpien kysymysten syöte:',
		'feed_for_qa' => 'Tuoreiden kysymysten ja vastausten syöte:',
		'feed_for_questions' => 'Tuoreiden kysymysten syöte:',
		'feed_for_search' => 'Hakutulosten syöte:',
		'feed_for_tag_qs' => 'Jokaisella tagilla oma syöte:',
		'feed_for_unanswered' => 'Vastaamattomien kysymysten syöte:',
		'feed_full_text' => 'Sisällytä koko teksti syötteissä:',
		'feed_number_items' => 'Syötteiden maksimipituus:',
		'feed_per_category' => 'Jokaisella kategorialla oma syöte:',
		'feedback_email' => 'Ylläpidon sähköpostiosoite - ei näytetä käyttäjille:',
		'feedback_enabled' => 'Salli käyttäjien palautteet',
		'flagging_hide_after' => 'Automatically hide posts which reach:',
		'flagging_notify_every' => 'Email me again after every additional:',
		'flagging_notify_first' => 'Email me if a post receives:',
		'flagging_of_posts' => 'Allow posts to be flagged:',
		'follow_on_as' => 'Allow questions to be related to answers:',
		'from_email' => 'Sender address for messages from site:',
		'hot_weight_a_age' => 'Kysymyksellä on uusi vastaus:',
		'hot_weight_answers' => 'Kysymyksellä on monta vastausta:',
		'hot_weight_q_age' => 'Kysymys on uusi:',
		'hot_weight_views' => 'Kysymystä on katsottu usein:',
		'hot_weight_votes' => 'Kysymyksellä on monta ääntä:',
		'links_in_new_window' => 'Open linked URLs in a new window:',
		'logo_height' => 'Logon korkeus:',
		'logo_show' => 'Näytä logo sivun otsiko-osassa',
		'logo_url' => 'Logon URL - absoluuttinen tai suhteessa Q2A:n juureen:',
		'logo_width' => 'Logon leveys:',
		'mailing_body' => 'Body text:',
		'mailing_enabled' => 'Enable mass mailings to all users',
		'mailing_from_email' => 'From email address:',
		'mailing_from_name' => 'From name:',
		'mailing_per_minute' => 'Maximum mailing rate:',
		'mailing_subject' => 'Subject line:',
		'match_1' => 'Narrowest',
		'match_2' => 'Narrower',
		'match_3' => 'Default',
		'match_4' => 'Wider',
		'match_5' => 'Widest',
		'match_ask_check_qs' => 'Similar questions matching:',
		'match_example_tags' => 'Example tags matching:',
		'match_related_qs' => 'Related questions matching:',
		'max_len_q_title' => 'Maximum length of question title:',
		'max_num_q_tags' => 'Maximum number of tags:',
		'max_rate_ip_as' => 'Rate limit for adding answers:',
		'max_rate_ip_cs' => 'Rate limit for posting comments:',
		'max_rate_ip_flags' => 'Rate limit for flagging posts:',
		'max_rate_ip_logins' => 'Rate limit for logging in:',
		'max_rate_ip_messages' => 'Rate limit for sending private messages:',
		'max_rate_ip_qs' => 'Rate limit for asking questions:',
		'max_rate_ip_registers' => 'Rate limit for user registrations:',
		'max_rate_ip_uploads' => 'Rate limit for uploading files:',
		'max_rate_ip_votes' => 'Rate limit for voting:',
		'max_rate_user_as' => 'Maximum answers per user per hour:',
		'max_rate_user_cs' => 'Maximum comments per user per hour:',
		'max_rate_user_flags' => 'Maximum flags per user per hour:',
		'max_rate_user_messages' => 'Maximum private messages per user per hour:',
		'max_rate_user_qs' => 'Maximum questions per user per hour:',
		'max_rate_user_uploads' => 'Maximum uploads per user per hour:',
		'max_rate_user_votes' => 'Maximum votes per user per hour:',
		'min_len_a_content' => 'Minimum length of answer:',
		'min_len_c_content' => 'Minimum length of comment:',
		'min_len_q_content' => 'Minimum length of question body:',
		'min_len_q_title' => 'Minimum length of question title:',
		'min_num_q_tags' => 'Minimum number of tags:',
		'moderate_anon_post' => 'Use moderation for anonymous posts:',
		'moderate_by_points' => 'Use moderation for users with few points:',
		'moderate_notify_admin' => 'Email me when a post needs moderation:',
		'moderate_points_limit' => 'Use moderation for users with less than:',
		'moderate_unconfirmed' => 'Use moderation if email not confirmed:',
		'neat_urls' => 'URL structure:',
		'notify_admin_q_post' => 'Email this address when a question is posted',
		'notify_users_default' => 'Check email notification box by default:',
		'option_default' => 'Default',
		'page_size_activity' => 'Length of All Activity page:',
		'page_size_ask_check_qs' => 'Maximum similar questions to show:',
		'page_size_ask_tags' => 'Maximum tag hints to show:',
		'page_size_home' => 'Length of Q&A page:',
		'page_size_hot_qs' => 'Length of Hot! page:',
		'page_size_q_as' => 'Maximum answers per page:',
		'page_size_qs' => 'Length of Questions page:',
		'page_size_related_qs' => 'Maximum related questions:',
		'page_size_search' => 'Search results per page:',
		'page_size_tag_qs' => 'Questions on each tag page:',
		'page_size_tags' => 'Length of Tags page:',
		'page_size_una_qs' => 'Length of Unanswered page:',
		'page_size_user_posts' => 'Posts on each user page:',
		'page_size_users' => 'Length of Users page:',
		'pages_prev_next' => 'Links to previous/next pages:',
		'permit_admins' => 'Administrators',
		'permit_all' => 'Anybody',
		'permit_block' => 'Blocking or unblocking user or IPs:',
		'permit_confirmed' => 'Registered users with email confirmed',
		'permit_create_admins' => 'Creating administrators:',
		'permit_create_eds_mods' => 'Creating editors and moderators:',
		'permit_create_experts' => 'Creating experts:',
		'permit_delete_users' => 'Deleting users:',
		'permit_editors' => 'Editors, Moderators, Admins',
		'permit_experts' => 'Experts, Editors, Moderators, Admins',
		'permit_moderators' => 'Moderators and Admins',
		'permit_points_confirmed' => 'Registered & email confirmed & enough points',
		'permit_points' => 'Registered users with enough points',
		'permit_see_emails' => 'Viewing user email addresses:',
		'permit_supers' => 'Super Administrators',
		'permit_users' => 'Registered users',
		'place_full_below_content' => 'Full width - Below content',
		'place_full_below_footer' => 'Full width - Below footer',
		'place_full_below_nav' => 'Full width - Below navigation',
		'place_full_top' => 'Full width - Top of page',
		'place_main_below_lists' => 'Main area - Below lists',
		'place_main_below_title' => 'Main area - Below title',
		'place_main_bottom' => 'Main area - Bottom',
		'place_main_top' => 'Main area - Top',
		'place_side_below_categories' => 'Side panel - Below categories',
		'place_side_below_sidebar' => 'Side panel - Below sidebar box',
		'place_side_last' => 'Side panel - Last',
		'place_side_top' => 'Side panel - Top',
		'points_a_selected' => 'Having your answer selected as the best:',
		'points_a_voted_max_gain' => 'Limit from up votes on each answer:',
		'points_a_voted_max_loss' => 'Limit from down votes on each answer:',
		'points_base' => 'Add for all users:',
		'points_multiple' => 'Multiply all points:',
		'points_per_a_voted_down' => 'Per down vote on your answer:',
		'points_per_a_voted_up' => 'Per up vote on your answer:',
		'points_per_q_voted_down' => 'Per down vote on your question:',
		'points_per_q_voted_up' => 'Per up vote on your question:',
		'points_post_a' => 'Posting an answer:',
		'points_post_q' => 'Posting a question:',
		'points_q_voted_max_gain' => 'Limit from up votes on each question:',
		'points_q_voted_max_loss' => 'Limit from down votes on each question:',
		'points_select_a' => 'Selecting an answer for your question:',
		'points_vote_down_a' => 'Voting down an answer:',
		'points_vote_down_q' => 'Voting down a question:',
		'points_vote_up_a' => 'Voting up an answer:',
		'points_vote_up_q' => 'Voting up a question:',
		'q_urls_remove_accents' => 'Remove accents from question URLs:',
		'q_urls_title_length' => 'Question title length in URLs:',
		'search_module' => 'Use search module:',
		'show_a_form_immediate' => 'Show answer form immediately:',
		'show_always' => 'Always',
		'show_c_reply_buttons' => 'Show reply button on comments:',
		'show_custom_answer' => 'Custom message on answer form - HTML allowed:',
		'show_custom_ask' => 'Custom message on ask form - HTML allowed:',
		'show_custom_comment' => 'Custom message on comment form - HTML allowed:',
		'show_custom_footer' => 'Custom HTML at bottom of every page:',
		'show_custom_header' => 'Custom HTML at top of every page:',
		'show_custom_home' => 'Custom content in home page instead of Q&A',
		'show_custom_in_head' => 'Custom HTML in <HEAD> section of every page:',
		'show_custom_register' => 'Custom message on register form - HTML allowed:',
		'show_custom_sidebar' => 'Custom HTML in sidebar box on every page:',
		'show_custom_sidepanel' => 'Custom HTML in side panel on every page:',
		'show_custom_welcome' => 'Custom message in email sent to new registered users:',
		'show_fewer_cs_count' => 'If partially hidden, show most recent:',
		'show_fewer_cs_from' => 'Partially hide comments if more than:',
		'show_full_date_days' => 'Show full date after:',
		'show_home_description' => 'Include <META> description for home page:',
		'show_if_no_as' => 'If no answers',
		'show_message_history' => 'Store and display private message history:',
		'show_never' => 'Never',
		'show_notice_visitor' => 'Notice at top for first time visitors - HTML allowed:',
		'show_notice_welcome' => 'Notice at top for new registered users - HTML allowed:',
		'show_selected_first' => 'Move selected answer to the top:',
		'show_url_links' => 'Detect and link URLs in posts:',
		'show_user_points' => 'Show points next to usernames:',
		'show_user_titles' => 'Show titles next to usernames:',
		'show_view_counts' => 'Show view count in question lists:',
		'show_when_created' => 'Show age of user posts:',
		'site_language' => 'Site language:',
		'site_maintenance' => 'Take site down for temporary maintenance',
		'site_theme_mobile' => 'Theme for mobiles:',
		'site_theme' => 'Site theme:',
		'site_title' => 'Q&A site name:',
		'site_url' => 'Preferred site URL:',
		'smtp_active' => 'Send email via SMTP instead of local mail',
		'smtp_address' => 'SMTP server address:',
		'smtp_authenticate' => 'Send SMTP username and password',
		'smtp_password' => 'SMTP password:',
		'smtp_port' => 'SMTP server port:',
		'smtp_secure_none' => 'None',
		'smtp_secure' => 'SMTP secure connection:',
		'smtp_username' => 'SMTP username:',
		'sort_answers_by' => 'Sort answers by:',
		'sort_time' => 'Time',
		'sort_votes' => 'Votes',
		'suspend_register_users' => 'Temporarily suspend new user registrations:',
		'tag_separator_comma' => 'Use comma as the only tag separator:',
		'tags_or_categories' => 'Question classification:',
		'votes_separated' => 'Show separate up and down votes:',
		'voting_on_as' => 'Allow voting on answers:',
		'voting_on_q_page_only' => 'Allow voting on question page only:',
		'voting_on_qs' => 'Allow voting on questions:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/