<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-main.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 vastaus',
		'1_comment' => '1 kommentti',
		'1_day' => '1 päivä',
		'1_disliked' => '1 ei-tykkäys',
		'1_flag' => '1 liputus',
		'1_hour' => '1 tunti',
		'1_liked' => '1 tykkäys',
		'1_minute' => '1 minuutti',
		'1_month' => '1 kuukausi',
		'1_point' => '1 piste',
		'1_question' => '1 kysymys',
		'1_second' => '1 sekunti',
		'1_tag' => '1 tagi',
		'1_user' => '1 käyttäjä',
		'1_view' => '1 katselu',
		'1_vote' => '1 ääni',
		'1_week' => '1 viikko',
		'1_year' => '1 vuosi',
		'add_category_x_favorites' => 'Lisää kategoria ^ suosikkeihini',
		'add_favorites' => 'Lisää suosikkeihini',
		'add_tag_x_favorites' => 'Lisää tagi ^ suosikkeihini',
		'all_categories' => 'Kaikki kategoriat',
		'anonymous' => 'anonyymi',
		'answer_edited' => 'vastausta muokattu',
		'answer_reshown' => 'vastaus näytetty uudelleen',
		'answer_selected' => 'vastaus valittu',
		'answered_qs_in_x' => 'Eniten vastattuja kysymyksiä: ^',
		'answered_qs_title' => 'Eniten vastauksia',
		'answered' => 'vastattu',
		'asked_related_q' => 'kysytty aiheeseen liittyviä kysymyksiä',
		'asked' => 'kysytty',
		'by_x' => 'by ^',
		'cancel_button' => 'Peruuta',
		'closed' => 'suljettu',
		'comment_edited' => 'kommenttia muokattu',
		'comment_moved' => 'kommentti siirretty',
		'comment_reshown' => 'kommentti näytetty uudelleen',
		'commented' => 'kommentoitu',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^day ^month, ^year',
		'date_format_this_year' => '^day ^month',
		'date_month_1' => 'Tam',
		'date_month_2' => 'Hel',
		'date_month_3' => 'Maa',
		'date_month_4' => 'Huh',
		'date_month_5' => 'Tou',
		'date_month_6' => 'Kes',
		'date_month_7' => 'Hei',
		'date_month_8' => 'Elo',
		'date_month_9' => 'Syy',
		'date_month_10' => 'Lok',
		'date_month_11' => 'Mar',
		'date_month_12' => 'Jou',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'muokattu',
		'field_required' => 'Ole hyvä ja kirjoita jotain tähän kenttään',
		'general_error' => 'Palvelinvirhe - ole hyvä ja yritä uudelleen.',
		'hidden' => 'piilotettu',
		'highest_users' => 'Käyttäjät, joille eniten pisteitä',
		'hot_qs_in_x' => 'Hot questions in ^',
		'hot_qs_title' => 'Kuumat kysymykset',
		'image_not_read' => 'Kuvaa ei pystytty lukemaan. Hyväksytyt tiedostotyypit ovat: ^',
		'image_too_big_x_pc' => 'Kuva on liian iso. Kuvan maksimikoko on ^% .',
		'in_category_x' => 'in ^',
		'ip_address_x' => 'IP-osoite ^',
		'logged_in_x' => 'Hei, ^',
		'max_length_x' => 'Maksimipituus on ^ merkkiä',
		'me' => 'minä',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Ole hyvä ja anna lisää tietoja - vähintään ^ merkkiä',
		'max_upload_size_x' => 'Maksimikoko lähetettäville tiedostoille on ^',
		'moved' => 'siirretty',
		'nav_account' => 'Tilini',
		'nav_activity' => 'Kaikki toiminta',
		'nav_admin' => 'Ylläpito',
		'nav_ask' => 'Kysy kysymys',
		'nav_categories' => 'Kategoriat',
		'nav_feedback' => 'Lähetä palautetta',
		'nav_home' => 'Koti',
		'nav_hot' => 'Kuumaa!',
		'nav_login' => 'Kirjaudu sisään',
		'nav_logout' => 'Kirjaudu ulos',
		'nav_most_answers' => 'Eniten vastauksia',
		'nav_most_recent' => 'Tuoreimmat',
		'nav_most_views' => 'Eniten katseluja',
		'nav_most_votes' => 'Eniten ääniä',
		'nav_no_answer' => 'Ei vastausta',
		'nav_no_selected_answer' => 'Ei valittua vastausta',
		'nav_no_upvoted_answer' => 'Ei äänestettyjä vastauksia',
		'nav_qa' => 'K&V',
		'nav_qs' => 'Kysymykset',
		'nav_register' => 'Rekisteröidy',
		'nav_tags' => 'Tagit',
		'nav_unanswered' => 'Vastaamatta',
		'nav_updates' => 'Päivitykset',
		'nav_users' => 'Käyttäjät',
		'no_active_users' => 'Aktiivisia käyttäjiä ei löytynyt',
		'no_answers_found' => 'Vastauksia ei löytynyt',
		'no_answers_in_x' => 'No answers in ^',
		'no_categories_found' => 'Kategorioita ei löytynyt',
		'no_category' => 'Ei kategoriaa',
		'no_comments_found' => 'Kommentteja ei löytynyt',
		'no_comments_in_x' => 'No comments in ^',
		'no_questions_found' => 'Kysymyksiä ei löytynyt',
		'no_questions_in_x' => 'No questions in ^',
		'no_related_qs_title' => 'Aiheeseen liittyviä kysymyksiä ei löytynyt',
		'no_results_for_x' => 'No results found for ^',
		'no_tags_found' => 'Tageja ei löytynyt',
		'no_una_questions_found' => 'Vastaamattomia kysymyksiä ei löytynyt',
		'no_una_questions_in_x' => 'No unanswered questions in ^',
		'no_unselected_qs_found' => 'Kysymyksiä ilman oikeaa vastausta ei löytynyt',
		'no_unupvoteda_qs_found' => 'Kysymyksiä, joilla ei yhtään äänestettyä vastausta, ei löytynyt',
		'page_label' => 'Sivu:',
		'page_next' => 'seuraava',
		'page_not_found' => 'Sivua ei löytynyt',
		'page_prev' => 'edellinen',
		'popular_tags' => 'Suosituimmat tagit',
		'questions_tagged_x' => 'Recent questions tagged ^',
		'recategorized' => 'uudelleenkategorioistu',
		'recent_activity_in_x' => 'Recent activity in ^',
		'recent_activity_title' => 'Tuoreimmat tapahtumat',
		'recent_as_in_x' => 'Recently answered questions in ^',
		'recent_as_title' => 'Tuoreimmat vastaukset',
		'recent_cs_in_x' => 'Recently added comments in ^',
		'recent_cs_title' => 'Tuoreimmat kommenttit',
		'recent_qs_as_in_x' => 'Recent questions and answers in ^',
		'recent_qs_as_title' => 'Tuoreimmat kysymykset ja vastaukset',
		'recent_qs_in_x' => 'Recent questions in ^',
		'recent_qs_title' => 'Tuoreimmat kysymykset',
		'related_qs_title' => 'Aiheeseen liittyvät kysymykset',
		'remove_favorites' => 'Poista suosikeistani',
		'remove_x_favorites' => 'Poista ^ suosikeistani',
		'reopened' => 'uudelleen avattu',
		'reshown' => 'uudelleen näytetty',
		'results_for_x' => 'Search results for ^',
		'retagged' => 'uudelleentagattu',
		'save_button' => 'Tallenna muutokset',
		'search_button' => 'Etsi',
		'search_explanation' => 'Ole hyvä ja kirjoita jotain hakukentään ja yritä uudelleen.',
		'search_title' => 'Esti tuloksia',
		'selected' => 'valittu',
		'send_button' => 'Lähetä',
		'suggest_ask' => 'Help get things started by ^1asking a question^2.',
		'suggest_category_qs' => 'To see more, click for all the ^1questions in this category^2.',
		'suggest_qs_tags' => 'To see more, click for the ^1full list of questions^2 or ^3popular tags^4.',
		'suggest_qs' => 'To see more, click for the ^1full list of questions^2.',
		'unanswered_qs_in_x' => 'Questions without answers in ^',
		'unanswered_qs_title' => 'Tuoreet kysymykset ilman vastausta',
		'unselected_qs_in_x' => 'Questions without a selected answer in ^',
		'unselected_qs_title' => 'Tuoreet kysymykset, joilla ei ole valittua vastausta',
		'unupvoteda_qs_in_x' => 'Questions without an upvoted answer in ^',
		'unupvoteda_qs_title' => 'Tuoreet kysymykset ilman yhtään äänestettyä vastausta',
		'upload_limit' => 'Liian monta tiedostonlähetystä - yritä uudelleen tunnin kuluttua',
		'view_q_must_confirm' => 'Please ^5confirm your email address^6 to view question pages.',
		'view_q_must_login' => 'Please ^1log in^2 or ^3register^4 to view question pages.',
		'viewed_qs_in_x' => 'Most viewed questions in ^',
		'viewed_qs_title' => 'Eniten katsotut kysymykset',
		'vote_disabled_down' => 'Vastaan äänestäminen on sallittua vain joillekin käyttäjille',
		'vote_disabled_hidden_a' => 'Et voi äänestää piilotettuja vastauksia',
		'vote_disabled_hidden_q' => 'Et voi äänestää piilotettuja kysymyksiä',
		'vote_disabled_level' => 'Äänestys on mahdollinen vain joillekin käyttäjille',
		'vote_disabled_my_a' => 'Et voi äänestää omaa vastaustasi',
		'vote_disabled_my_q' => 'Et voi äänestää omaa kysymystäsi',
		'vote_disabled_q_page_only' => 'Ole hyvä ja tarkastele kysymystä äänestääksesi',
		'vote_down_must_confirm' => 'Please ^5confirm your email address^6 to vote down.',
		'vote_down_popup' => 'Klikkaa äänestääksesi vastaan',
		'vote_limit' => 'Liian monta ääntä lähetetty - kokeile uudestaan tunnin kuluttua',
		'vote_must_confirm' => 'Please ^5confirm your email address^6 to vote.',
		'vote_must_login' => 'Please ^1log in^2 or ^3register^4 to vote.',
		'vote_not_allowed' => 'Tätä ei voi äänestää',
		'vote_up_popup' => 'Klikkaa äänestääksesi',
		'voted_down_popup' => 'Olet äänestänyt tätä vastaan - klikkaa peruuttaaksesi',
		'voted_qs_in_x' => 'Highest voted questions in ^',
		'voted_qs_title' => 'Eniten ääenstetyt kysymykset',
		'voted_up_popup' => 'Olet äänestänyt tätä - klikkaa poistaaksesi äänesi',
		'x_ago' => '^ sitten',
		'x_answers' => '^ vastausta',
		'x_comments' => '^ kommenttia',
		'x_days' => '^ päivää',
		'x_disliked' => '^ ei-tykkäystä',
		'x_flags' => '^ liputusta',
		'x_hours' => '^ tuntia',
		'x_liked' => '^ tykkäystä',
		'x_minutes' => '^ minuuttia',
		'x_months' => '^ kuukautta',
		'x_points' => '^ pistettä',
		'x_questions' => '^ kysymystä',
		'x_seconds' => '^ sekuntia',
		'x_tags' => '^ tagia',
		'x_users' => '^ käyttäjää',
		'x_views' => '^ katselukertaa',
		'x_votes' => '^ ääntä',
		'x_weeks' => '^ viikkoa',
		'x_years' => '^ vuotta',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/